name: weather_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  google_fonts: ^8.0.0
  intl: ^0.20.2
  liquid_glass_renderer: ^0.2.0-dev.4
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
